#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

if [ -d /init.d ]; then
  for f in /init.d/*; do
    . "$f"
  done
fi
echo "Successfully booted vm"
exec /bin/sh
